### PR TITLE
feat(assertions): add support for json matchers negation

### LINKED ISSUE #42: Add support for not contains json matcher
Hi everyone.

I created this issue instead of a PR to talk about it with you first. I'm still 100% motivated to code it myself though.

Here's the issue: Today we can't make an **explicit**, **concise** and **human readable** test that a JSON field doesn't contain a string.

How about adding a way to negate matchers or add new negated matchers `not contain` / `not contains` ? (or even `!contains`)

# Example / Use case
Let's say I want to test this object : 
```
{
  a: string
  b: string
}
```

Additionally `a` and `b` :
- have very, very **long values** (e.g. URLs with many query params, tokens, etc.)
- might **evolve many times** in the project lifecycle (e.g. by adding params regularly)

=> **I don't want to use the `equals` matcher** because I'll have to update every tests every time, plus my tests would be over verbose.

Now let's pretend that I have to develop a new feature where:
- I need to add a new `foo` query param only for `a`
- But absolutely not for `b` (i.e. they have a similar method of generation and errors could be made)

I'd want to test that :
- `a` contains `foo`
- `b` does not contain `foo`

And here's what it would look like today :
```
And json response should match
    | field | matcher  | value         |
    | a     | contains | foo           |
    | b     | match    | ^((?!foo).)*$ |
```

The only way to do the second test is to match the value against `^((?!foo).)*$` with `match`, which is not really human readable and more error prone than a simple `not contains`.

The negated contains would look like this:
```
And json response should match
    | field | matcher      | value |
    | a     | contains     | foo   |
    | b     | not contains | foo   |
```

WDYT @plouc @leguellec ?

# TL;DR
Need to test if a value is not contained by another one, but regexps are not human friendly :

tenor

### PR DESCRIPTION
**Pull request by Crow-EH**
Closes #42

### CODE REVIEW

**Comment by plouc** [comment]
There's [an existing PR](https://github.com/ekino/veggies/pull/41) which changes the way me detect the matcher. Maybe you should work from it instead of master.

**Comment by Crow-EH** [comment]
Yeah, it'll allow for a cleaner code, especially if I have to negate every matchers.

**Comment by Crow-EH** [comment]
@plouc I rebased on @matthyy 's branch. :+1:

**Comment by plouc** [comment]
@Crow-EH, thank you! I'll have a look at it when @matthyy's PR gets merged.

**Comment by Crow-EH** [comment]
@plouc It seems like #41 droped the regex matching of assertions.

Since it's really usefull, I kept it and rebased on master directly.

**Comment by Crow-EH** [comment]
The way to use the negation is to **start** your matcher phrase with any of these:
* `not`
* `does not`
* `doesn't`
* `is not`
* `isn't`
* `!`
and **finish** with any existing assertion keywords :
* `match` / `matches`
* `contain` / `contains`
* `defined` / `present`
* `equal` / `equals`
* `type`

I think it's the most lenient way to do it, but it has the side effect to permit words between negation and assertion (which could be a way to write more expressive phrases too).

**Comment by Crow-EH** [comment]
Reopened in #48 (source branche mishap)

**Pull request closed without merging**
