### PR TITLE
Add multipart

### PR DESCRIPTION
**Pull request by mnishizawa**
Adds support for multipart forms for file upload via a service call.

Note: a lot of the files here are simply reformatted though I didn't touch them and never opened them.  Not sure if that is happening in the precommit hooks but I thought I would bring it up that I did not reformat those files.

I don't see any other test frameworks for apis that support multipart form submission for file upload. 

**Test plan**
Definition test has been added to the rest of the definitions tests.  

When I use the step definition, "[I ]set request multipart body from <module fixture>", the request will create a request for a multipart form submission.

Sample fixture:
```JavaScript
'use strict'

const fs = require('fs')

module.exports = () => ({
    "errorLog" : fs.createReadStream(__dirname+"/sampleErrorFile.txt.zip")
})
```

### CODE REVIEW

**Comment by plouc** [comment]
@mnishizawa, thank you for this contribution, for the updated files you didn't touched, that's probably because you're using npm instead of yarn, this repo provides a yarn.lock.
There's a git hook which format files, because npm didn't used lock file, you may have a different prettier version which formatted code differently. Is it possible that you switch to yarn and re-format the code please?

**Comment by mnishizawa** [comment]
When I commit the husky hooks appear to still be running npm.  Is there something I need to do to tell it to run yarn instead?

**Comment by plouc** [comment]
Sorry, I meant just running the install through yarn, npm should be fine after that, it's just to lock deps.

**Comment by mnishizawa** [comment]
Ok, files should be updated now, one of the snapshot tests failed.  Any guidance on how I may have affected that test since I didn't change anything in the snapshots extension?

**Comment by plouc** [comment]
Fail was due to a timeout, just restarted it, and it passed.

**Comment by mnishizawa** [comment]
Cool.  Anything else you would like me to fix?

**Comment by plouc** [comment]
Nope, LGTM, thank you!

**Pull request merged**
