### PR TITLE
Adding PATCH to the acceptable request methods and a notPresent check for the json body

### PR DESCRIPTION
**Pull request by mnishizawa**
**Summary**
1. Added PATCH to the list of acceptable methods
2. Added notPresent to the json body checks 

In our testing we test endpoints that use the PATCH method as well as we want to check if fields are not present in the json body.  We wanted to offer this back to the main project if you so choose.

**Test plan**
We have tested this code against our codebase and test project.

### CODE REVIEW

**Comment by mnishizawa** [comment]
PR #34 has the requested modifications. This one can be closed.

**Comment by mnishizawa** [comment]
@plouc For some reason I am not able to add you as a reviewer but if you would be so kind as to review and merge this it would allow our project to point our dependencies back to the main repo instead of working off our fork.

**Comment by plouc** [comment]
@mnishizawa, it seems something went wrong with git, can you please rebase this PR?

**Comment by Crow-EH** [comment]
Hi @mnishizawa 
We just merged the support for negation of every matchers. :tada:
You can now check for the absence  of your field with `not present`, `!present`, `is not present` and so on.
Can you rebase your work and only include the support for `PATCH` ?
Thank you! :+1:

**Comment by pebie** [comment]
Work has been done in this [PR](https://github.com/ekino/veggies/pull/64)

**Pull request closed without merging**
